#:schema node_modules/wrangler/config-schema.json
name = "pinguendo"
main = "src/index.ts"
compatibility_date = "2024-10-18"

[vars]
PING_TARGET = "http://localhost:8787"

[triggers]
crons = ["*/5 * * * *"] # */5 * * * * = run every 5 minutes

[observability]
enabled = true
